/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.norbl.cbp.ppe.usermonitor;

import com.norbl.cbp.ppe.*;
import com.norbl.util.gui.*;
import java.awt.event.*;

/**
 *
 * @author moi
 */
public class AuthorizationFrame extends javax.swing.JFrame {

    AuthorizationClient client;
    
    /**
     * Creates new form AuthorizationFrame
     */
    public AuthorizationFrame(AuthorizationClient client) {
        this.client = client;
        SwingDefaults.setIcon(this);
        this.client = client;
        this.setTitle("Billing Authorization");      
        initComponents();
        WevHandler wev = new WevHandler();
        this.addWindowListener(wev);
        GuiUtil.centerOnScreen(this);
        this.setVisible(true);
        this.setAlwaysOnTop(true);
    }

    public String getEmailAddress() {
        return(emailEntryJTextField.getText());
    }
    
    class WevHandler extends WindowAdapter {        
        public void windowClosing(WindowEvent e) {    
            client.windowClosed();         
        }
        public void windowClosed(WindowEvent e) {           
            client.windowClosed();    
        }
    }
    
    static String text =
            "<html>" +
            "We charge " + ConstantsUM.PRICE_PIPH  + 
                           " per instance per hour for the use of our<br>" +
            "most recent machine images (AMIs).  This charge is in addition<br>" +
            "to Amazon's instance and data transfer charges and is billed<br>" +
            "<i>separately</i>, through Amazon's payment system.<br><br>" +
    
            "To authorize billing, enter an email address, which we'll<br>" +
            "use as your ID for billing purposes. This email address will<br>" +
            "<i>not</i> added to any mailing lists and will <i>not</i> be given to<br>" +
            "anyone. You will be billed monthly if and when the amount<br>" +
            "due is > $10.00 US.  If your total never exceeds $10.00 you will<br>" +
            "never be billed and will not owe anything.<br><br>" +
    
            "After you enter the email address, your browser will be<br>" +
            "launched displaying Amazon's page for authorizing the billing."
            + "</html>";               
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleJLabel = new javax.swing.JLabel();
        textJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        emailEntryJTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        continueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleJLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 15)); // NOI18N
        titleJLabel.setText("Enter email address for billing authorization");

        textJLabel.setText(text);

        emailJLabel.setText("Email address");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(client);
        cancelButton.setActionCommand("cancel");

        continueButton.setText("Continue");
        continueButton.addActionListener(client);
        continueButton.setActionCommand("continue");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(emailJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailEntryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(continueButton)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleJLabel)
                            .addComponent(textJLabel))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(titleJLabel)
                .addGap(43, 43, 43)
                .addComponent(textJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailJLabel)
                    .addComponent(emailEntryJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(continueButton))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthorizationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthorizationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthorizationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthorizationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                com.norbl.util.gui.GuiMetrics.init();    
                com.norbl.util.gui.SwingDefaults.setDefaults();
                new AuthorizationFrame(null).setVisible(true);
                }
                catch(Exception xxx) { throw new RuntimeException(xxx); }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JTextField emailEntryJTextField;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textJLabel;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
