/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestFrame.java
 *
 * Created on Feb 29, 2012, 10:19:02 PM
 */
package ppe.gui.networkspec;

import java.awt.event.*;
import javax.swing.*;
import nbl.utilj.*;

/**
 *
 * @author moi
 */
public class TestFrame extends javax.swing.JFrame implements ActionListener {

    
     NetworkSpecGui spec;
     boolean on;
    
    
    /** Creates new form TestFrame */
    public TestFrame(NetworkSpecGui spec) {
        this.spec = spec;
        
    }
    
    public void create() {  
        
        GuiMetrics.init();
        
        on = false;
        
        initComponents();
        ppe.gui.SwingDefaults.setIcon(this);
        instanceTypeRBMenu.build(spec.instanceTypeChoices, 
                                 this,spec.instanceTypeChoices.size()); 
        
//        amiRBMenu.build(spec.amiChoices, this,spec.amiChoices.size());
        
        
        GuiUtil.centerOnScreen(this);        
        this.setVisible(true);
        
    }

    public void actionPerformed(ActionEvent ev) {
    
        System.out.println("ACTION " + ev);
        
        String c = ev.getActionCommand();
        if ( c.equals("button") ) {
            if ( !on ) {               
                amiRBMenu.build(spec.amiChoices, this,spec.amiChoices.size());
                amiRBMenu.revalidate();
                this.repaint();
                on = true;
            }
            else {
                amiRBMenu.emptyMenu();
                amiRBMenu.emptyMenu();
                amiRBMenu.revalidate();
                this.repaint();
                on = false;
            }
        }
    
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instanceTypeRBMenu = new ppe.gui.networkspec.ChoiceMenu();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        amiRBMenu = new ppe.gui.networkspec.ChoiceMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout instanceTypeRBMenuLayout = new javax.swing.GroupLayout(instanceTypeRBMenu);
        instanceTypeRBMenu.setLayout(instanceTypeRBMenuLayout);
        instanceTypeRBMenuLayout.setHorizontalGroup(
            instanceTypeRBMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        instanceTypeRBMenuLayout.setVerticalGroup(
            instanceTypeRBMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        jLabel1.setText("A Title");

        jButton1.setText("jButton1");
        jButton1.setActionCommand("button");
        jButton1.addActionListener(this);

        javax.swing.GroupLayout amiRBMenuLayout = new javax.swing.GroupLayout(amiRBMenu);
        amiRBMenu.setLayout(amiRBMenuLayout);
        amiRBMenuLayout.setHorizontalGroup(
            amiRBMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        amiRBMenuLayout.setVerticalGroup(
            amiRBMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amiRBMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(instanceTypeRBMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 573, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(171, 171, 171))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addComponent(instanceTypeRBMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(amiRBMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(472, 472, 472))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
////            public void run() {
////                new TestFrame().setVisible(true);
////            }
//        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ppe.gui.networkspec.ChoiceMenu amiRBMenu;
    private ppe.gui.networkspec.ChoiceMenu instanceTypeRBMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
